---
output:
  html_document:
    toc: true
    toc_float: true
---

# Professional

---


HAGERTY CONSULTING | CALIFORNIA DEPARTMENT OF PUBLIC HEALTH | Sacramento, CA

**PUBLIC HEALTH CONSULTANT: PROJECT MANAGER AND EPIDEMIOLOGIST | AUGUST 2020 - PRESENT** 

*	Worked on site at the California Department of Public Health for the California Vaccine Task Force 
*	Managed day to day communications and operations of California’s COVID-19 Vaccine Task Force under CA Department of Public Health leadership.
* Created organizational structure and maintained documentation of structure as entities and responsibilities changed throughout the response.
*	Created initial work groups, objectives associated with work stream, and tracked success based on completion of tasks towards objectives. 
*	Create organizational structure, objectives, tasks, and overarching plan for the CDPH Vaccine Task Force  
* Generated SQL code to analyze and build COVID-19 vaccination rate reports that helped inform where to invest more resources to improve overall vaccination.
*	Built maps via Tableau and SAS to illustrate vaccination equity at the zip code level as a tool for counties to gain a clearer picture of how to assist their communities with less healthy conditions.
*	Assisted in the creation and implementation of a vaccine equity metric that was used to determine vaccine allocation during times of vaccine scarcity.


NYC DEPARTMENT OF HEALTH AND MENTAL HYGIENE | Queens, NY

**GRADUATE RESEARCH INTERN | JUNE 2019 - AUGUST 2020**

*	Created Standard Operating Procedure for quarterly review and analysis of mental health assessment and electronic health record data from 7 early childhood mental health therapeutic centers across NYC
* Reviewed electronic health record data for missing data and inaccurate diagnosis/procedure codes to improve quality of data
*	Cleaned and organized the 28 datasets from 7 clinics using SAS macros for merging into a comprehensive  dataset for annual monitoring purposes 
*	Ran descriptive and bivariate analyses to evaluate clinic utilization for each Early Childhood Therapeutic Center
*	Supported the Project Director and the Evaluation and Quality Improvement Specialist in the creation of annual analysis plan and wrote SAS programs per plan

EDVANCE AT SAN FRANCISCO STATE UNIVERSITY | San Francisco, CA

**Fiscal Incentives Coordinator | October 2017 - March 2018**

*	Created and distributed outreach materials, including fliers, social media posts, email blasts and telephone calls regarding information about our four distinct early childhood workforce development programs 
*	Collected, compiled, analyzed and updated applicant data to the California Early Care & Education Registry
*	Conducted over 50 presentations in college classrooms, preschool staff meetings, and career fairs to provide detailed information about our financial incentive program and application processes
*	Tracked 400+ student applications and assisted those students via phone and email to complete all materials necessary to receive their stipends
*	Collaborated with stakeholders in the area to provide comprehensive support for applicants 


ONE MEDICAL | San Francisco, CA

**Billing Specialist | December 2015 - September 2017**

*	Collaborated primary care team, medical specialists, billing specialists, health insurance companies and patients to remove any possible barriers to care
*	Monitored  administrative team efficiency via tableau and proposed methods of practice improvement
*	Educated patients about their specific medical coverage and benefits in office and via email and telephone
*	Investigated billing charges and posted any claim payments to our internal payment system
*	Worked as a liaison between medical team and patients to address immediate health concerns 


SFSU CHILD AND ADOLESCENT DEVELOPMENT DEPARTMENT | Vrygrond, Capetown 

**Teacher/Facilitator | June - July 2015**

*	Implemented ECE curricula township preschools by assisting preschool teachers daily with lesson planning, material organizing, and problem solving
*	Collaborated with teams to design and hold professional development events to build cross-cultural community
*	Reinforced effective teaching methods with limited resources to ensure scalability for larger class sizes
*	Promoted and sustained clean and safe environment for students through classroom organizing and evaluations
	
SAN FRANCISCO DEPARTMENT OF PUBLIC HEALTH	| San Francisco, CA

**Project Coordinating Intern | August 2014 - May 2015**

*	Managed communication and logistics for SFDPH and the Trauma Informed Systems Initiative 
*	Researched, developed and implemented employee trainings for 250+ participants per session
*	Facilitated monthly on-boarding programs for new trainer cohorts

# Technical Skills

---


**RedCap | R | SAS Enterprise | SAS | Tablaeu | Microsoft Office**

# Certifications

---


**HIPPA Certification (2018) | CITI Certification(2018) | Columbia University Epidemiology of Chronic Disease Certificate | Metro Academies Child and Adolescent Development Certificate(2015)**

# Academic

---

COLUMBIA UNIVERSITY, MAILMAN SCHOOL OF PUBLIC HEALTH

**Master of Public Health: Epidemiology (May 2020)**  

SAN FRANCISCO STATE UNIVERSITY 

**Bachelor of Science in Health Education (May 2015)** 

# Other Activities 

---

[Columbia University Mailman School of Public Health Students of Color Celebration Speaker](Presentation.html) | May 2020

[R.I.S.E. (Resilience, Inclusion, Solidarity, and Empowerment) Mentor](https://www.publichealth.columbia.edu/research/office-diversity-culture-and-inclusion/rise-peer-mentor-program) | 2019-2020

[2nd Annual Gun Violence Action Week Organizer](Action_week.html)  | November 2019 

# Poster Presentations

---

[Early Childhood Mental Health Network Early Childhood Therapeutic Centers EHR Review](Poster.html) | October 2019
