---
title: "My first dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    code_folding: hide
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(flexdashboard)
library(plotly)
```

```{r}
set.seed(1)

data("instacart")
nyc_instacart = 
  instacart %>% 
  select(
    user_id, reordered, product_name, order_hour_of_day, aisle) %>% 
  sample_n(5000)
```

Column {data-width=650}
-----------------------------------------------------------------------


### Chart A

```{r}
nyc_instacart %>% 
  group_by (product_name, reordered, aisle) %>%
  summarise(n = n()) %>%
  filter(n %in% 5:25) %>% 
  plot_ly(x = ~ n, y = ~ product_name, type = "scatter", mode = "markers", color= ~aisle, alpha = 0.5)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
nyc_instacart %>%
  filter(aisle== c( "juice nectars", "water seltzer sparkling water", "fresh fruits","fresh vegetables", "packaged vegetables fruits")) %>% 
  group_by (aisle, product_name) %>% 
  summarize(n=n()) %>%
  plot_ly(y = ~n, x= ~aisle, color = ~aisle, type = "bar") %>%
  layout(
    xaxis = list(
      categoryorder = "array",
      categoryarray = ~c("fresh fruits","fresh vegetables", "packaged vegetables fruits", "water seltzer sparkling water", "juice nectars") )
    )
```

### Chart C

```{r}
nyc_instacart %>%
  filter(aisle== c("fresh fruits", "fresh vegetables"), order_hour_of_day %in% 5:15 ) %>% 
  group_by (aisle, product_name, order_hour_of_day) %>% 
  summarize(n=n()) %>%
  plot_ly(y =  ~product_name, x=~order_hour_of_day, color=~aisle, mode = "line", type = "scatter")
```
