---
title: "Speech"
output: 
  html_document
---

**Columbia University Mailman School of Public Health Students of Color Celebration 2020**

<video src="TSpeech.m4v" width="620" height="400" controls preload></video>


<p>
<center>"The Office of Diversity, Culture, and Inclusion (ODCI), The Black & Latinx Student Caucus (BLSC), Advocates for Asian American Health (AAAH) and the Office of Student Affairs (OSA) are pleased to support the Mailman School of Public Health Students of Color (SOC) Graduation Ceremony. SOC graduation ceremonies have long been held at Columbia University and other leading academic institutions to celebrate the contributions made by students of color to the advancement of scholarship, leadership, service, and community development. Columbia’s Office of Multicultural Affairs has hosted similar ceremonies for undergraduate students. However, the [Mailman School’s SOC Graduation Ceremony](https://www.publichealth.columbia.edu/research/office-diversity-culture-and-inclusion/students-color-ceremony) is the first to be held for the school’s graduate and doctoral students of color."</center>
</p>